version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-1)
  build:
    commands:
      - echo build Docker image on `date`
      - cd src
      - docker build -t 632628322532.dkr.ecr.eu-west-1.amazonaws.com/tooling-repo/sanportal:latest .
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 632628322532.dkr.ecr.eu-west-1.amazonaws.com/tooling-repo/sanportal:latest
